# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0013_auto_20180131_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcomponent',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='releasecomponent',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
